backend:
  name: git-gateway

media_folder: public/img
public_folder: /img

collections:
  - name: 'docs'
    label: 'Docs'
    folder: 'docs'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }